name: Docker Compose CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Start services
        run: |
          docker compose up -d
          sleep 15

      - name: Wait for web service
        run: |
          for i in {1..30}; do
            echo "Attempt $i: testing http://localhost:5000/"
            if curl -fsS http://localhost:5000/; then
              echo "Web responded OK"
              break
            fi
            sleep 2
          done

      - name: Test DB connection via Flask
        run: curl -fsS http://localhost:5000/db

      - name: Debug logs if failed
        if: failure()
        run: docker compose logs --no-color
